name: bia
services:
  server:
    container_name: bia
    environment:
      DB_HOST: bia-eb.c29gca8kizzb.us-east-1.rds.amazonaws.com
      DB_PORT: "5432"
      DB_PWD: postgres10
      DB_USER: postgres
    image: 448522291635.dkr.ecr.us-east-1.amazonaws.com/bia:97234bf
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
networks:
  default:
    name: bia_default
