services:
  server:
    container_name: bia
    image: 448522291635.dkr.ecr.us-east-1.amazonaws.com/bia:e2b0571
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
