services:
  bia:
    container_name: bia
    image: 448522291635.dkr.ecr.us-east-1.amazonaws.com/bia:c43449b
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
