services:
  server:
    image: 448522291635.dkr.ecr.us-east-1.amazonaws.com/bia:${TAG}
    container_name: bia
    ports:
      - 80:8080
    
    environment:
      DB_USER: postgres
      DB_PWD: postgres10
      DB_PORT: 5432
      DB_HOST: bia-dev-beanstalk.c29gca8kizzb.us-east-1.rds.amazonaws.com
      