services:
  bia:
    env_file: .env
    container_name: bia
    environment:
      TAG: 2bc1afc
    image: 448522291635.dkr.ecr.us-east-1.amazonaws.com/bia:2bc1afc
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
