services:
  bia:
    env_file: .env
    container_name: bia
    environment:
      TAG: "0067844"
    image: 448522291635.dkr.ecr.us-east-1.amazonaws.com/bia:0067844
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
