services:
  bia:
    env_file: .env
    container_name: bia
    environment:
      DB_HOST: bia-eb.c29gca8kizzb.us-east-1.rds.amazonaws.com
      DB_PASSWORD: postgres10
      DB_PORT: "5432"
      DB_USER: postgres
    image: 448522291635.dkr.ecr.us-east-1.amazonaws.com/bia:579a530
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
